name: routesyncui
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_osm_plugin: ^1.3.6
  http: ^1.2.2
  geofencing_api: ^2.0.0
  permission_handler: ^11.3.1
  auto_size_text: ^3.0.0
  supabase_flutter: ^2.8.3
  table_calendar: ^3.2.0
  geolocator: ^13.0.2
  flutter_map_geojson: ^1.0.8
  mapbox_maps_flutter: ^2.5.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true       # Enable Android platform
  ios: true           # Enable iOS platform
  image_path: "assets/logo/ic_launcher.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
      - family: AirbnbCereal
        fonts:
          - asset: assets/fonts/AirbnbCereal_W_Bk.otf       
          - asset: assets/fonts/AirbnbCereal_W_Blk.otf     
          - asset: assets/fonts/AirbnbCereal_W_Md.otf       
          - asset: assets/fonts/AirbnbCereal_W_XBd.otf      
          - asset: assets/fonts/AirbnbCereal_W_Lt.otf      
          - asset: assets/fonts/AirbnbCereal_W_Bd.otf

      - family: AirbnbCereal-Bold
        fonts:
          - asset: assets/fonts/AirbnbCereal_W_Bk.otf  
           

      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf        
          - asset: assets/fonts/Poppins-Medium.ttf        
          - asset: assets/fonts/Poppins-SemiBold.ttf        
          - asset: assets/fonts/Poppins-Bold.ttf      
          - asset: assets/fonts/Poppins-ExtraBold.ttf         
          - asset: assets/fonts/Poppins-Black.ttf
          
      - family: Manrop
        fonts:
          - asset: assets/fonts/Manrope-SemiBold.ttf        
